#!/usr/bin/env bash


#  9 is an Armstrong number, because 9 = 9^1 = 9
#  10 is not an Armstrong number, because 10 != 1^2 + 0^2 = 1
#  153 is an Armstrong number, because: 153 = 1^3 + 5^3 + 3^3 = 1 + 125 + 27 = 153
#  154 is not an Armstrong number, because: 154 != 1^3 + 5^3 + 4^3 = 1 + 125 + 64 = 190

num=

for (( i=0; i<${#1}; i++ )); do
  num=$((num + ((${1:i:1}**${#1}))))
done

if (( $1 == $num )); then
  echo "Armstrong number"
else
  echo "There is no armstrong number"
fi

exit 0
