#!/usr/bin/env bash

# The goal of this exercise is to consider the number of arguments passed to
# your program. If there is exactly one argument, print a greeting message.
# Otherwise print an error message and exit with a non-zero status.

case $# in
  1 ) echo "Welcome to the $(basename $0)"
      exit 0
    ;;
  * ) echo "ERROR"
      exit 1
esac
