#!/usr/bin/env bash


#  has 3 as a factor, add 'Pling' to the result.
#  has 5 as a factor, add 'Plang' to the result.
#  has 7 as a factor, add 'Plong' to the result.
#  does not have any of 3, 5, or 7 as a factor, the result should be the digits of the number.

main () {
accum_of_text=

if (( $1 % 3 == 0 )); then
  accum_of_text=$accum_of_text"Pling"
fi

if (( $1 % 5 == 0 )); then
  accum_of_text=$accum_of_text"Plang"
fi

if (( $1 % 7 == 0 )); then
  accum_of_text=$accum_of_text"Plong"
fi

if [[ -n "$accum_of_text" ]]; then
  echo $accum_of_text
else
  echo "\"$1\""
fi
}
main "$@"
